name: CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        node-version:
          - 6

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        uses: bahmutov/npm-install@v1

      - name: Install Coveralls
        run: npm install coveralls

      - name: Coverage
        run: npm run coverage

      - name: Coverage Report
        run: npm run coveralls
