name: CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        node-version:
          - 15

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set up GCC
        run: |-
          curl https://musl.libc.org/releases/musl-1.2.2.tar.gz -o musl-1.2.2.tar.gz
          tar -xvf musl-1.2.2.tar.gz
          cd musl-1.2.2
          ./configure
          make 
          make install
          ln -s /usr/lib64/libc.so.6 /usr/lib64/libc.musl-x86_64.so.1
          cd ..

      - name: Install
        # potential optimization
        # uses: bahmutov/npm-install@v1
        run: npm i

      - name: Test
        run: npm t

      # - name: Install Coveralls
      #   run: npm install coveralls

      # - name: Coverage
      #   run: npm run coverage

      # - name: Coverage Report
      #   run: npm run coveralls
